import pygame

SEED = 100
SCREEN_WIDTH, SCREEN_HEIGHT = (1000,600)
PLATFORM_SIZE = 2000
SCREEN = pygame.display.set_mode((SCREEN_WIDTH,SCREEN_HEIGHT))
GRID_SIZE = 50
SIZE_OF_FOOD = 5
NB_FOOD = PLATFORM_SIZE * 2
NB_BOTS = 0
NB_PARTICLES = 10
DEFAULT_MASS = 15
DEFAULT_MASS_BOT = 15
DIFF_TO_EAT = 2